version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: backend-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
      context: ../student-nexus-frontend
    container_name: frontend-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ../student-nexus-frontend/.env

  redis:
    image: redis:7-alpine
    container_name: student-nexus-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local