name: Deploy to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_BACKEND_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Go to backend"
            cd ${{ secrets.EC2_BACKEND_TARGET_DIR }}

            echo "Pull backend"
            git pull origin main

            echo "Go to frontend"
            cd ../student-nexus-frontend

            echo "Pull frontend"
            git pull origin main

            echo "Restart Docker"
            cd ../student-nexus-backend
            docker-compose down
            docker-compose up -d --build
