name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_BACKEND_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            BASE_DIR="/var/www/html/myapp"
            cd $BASE_DIR

            echo "Setup backend repo"
            if [ ! -d "student-nexus-backend/.git" ]; then
              git clone git@github.com:SinghRiya05/student-nexus-backend.git
            else
              cd student-nexus-backend
              echo "Stashing local changes..."
              git stash
              echo "Pulling latest changes..."
              git pull origin main
              echo "Restoring local changes..."
              git stash pop || true
              cd ..
            fi

            echo "Restart ONLY backend"
            cd student-nexus-backend
            docker compose up -d --build backend